version: '3.8'

services:
  # Carla ROS bridge container
  custom_carla_bridge:
    build:
      context: .
      dockerfile: ./docker/custom_carla_bridge/Dockerfile
    image: custom-carla-bridge:latest
    container_name: custom-carla-bridge
    command: ros2 launch custom_carla_bridge carla_ros_node.launch.py host:=192.168.1.73 town:=Town07_Opt
    volumes:
      - ./:/ros2_ws
    restart: always

  # foxglove to visualize live data 
  foxglove_bridge:
    build:
      context: .
      dockerfile: ./docker/foxglove_bridge/Dockerfile

    image: foxglove-bridge:latest
    ports:
      - 8765:8765
    container_name: foxglove_bridge
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765
    restart: always
    depends_on:
      custom_carla_bridge:
        condition: service_started

networks:
  hostnet:
    external: true
